const PDFDocument = require('pdfkit');

const generatePdfReport = async (analysis = {}) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Title
      doc.fontSize(24).text('PolicyGuard AI Report', { align: 'center' });
      doc.moveDown(2);

      // Basic info
      doc.fontSize(14);
      doc.text(`Source: ${analysis.source || 'Unknown'}`);
      doc.text(`Risk Score: ${analysis.riskScore ?? analysis.riskScore === 0 ? analysis.riskScore : (analysis.analysis?.riskScore || 0)}`);
      doc.text(`Risk Level: ${analysis.riskLevel || analysis.analysis?.riskLevel || 'Unknown'}`);
      doc.text(`Confidence: ${analysis.confidence ?? analysis.analysis?.confidence ?? 0}%`);
      doc.moveDown();

      // Summary
      doc.fontSize(18).text('Summary', { underline: true });
      doc.moveDown(0.5);
      const summary = analysis.summary || analysis.analysis?.summary || 'No summary available.';
      doc.fontSize(12).text(summary);
      doc.moveDown(1.5);

      // Risks
      doc.fontSize(18).text('Detected Risks', { underline: true });
      doc.moveDown(0.5);
      const risks = Array.isArray(analysis.risks) && analysis.risks.length ? analysis.risks : (Array.isArray(analysis.analysis?.risks) ? analysis.analysis.risks : []);
      if (risks.length) {
        risks.forEach((risk, i) => doc.fontSize(12).text(`${i + 1}. ${risk}`));
      } else {
        doc.fontSize(12).text('No risks detected.');
      }
      doc.moveDown(1.5);

      // Clauses
      doc.fontSize(18).text('Risky Clauses', { underline: true });
      doc.moveDown(0.5);
      const clauses = Array.isArray(analysis.clauses) && analysis.clauses.length ? analysis.clauses : (Array.isArray(analysis.analysis?.clauses) ? analysis.analysis.clauses : []);
      if (clauses.length) {
        (clauses || []).slice(0, 10).forEach((clause, idx) => {
          const clauseText = clause?.clause || typeof clause === 'string' ? clause : 'N/A';
          const type = clause?.type || 'Unknown';
          const severity = clause?.severity || 'Unknown';
          const explanation = clause?.explanation || 'No explanation';

          doc.fontSize(12).text(`${idx + 1}. ${String(clauseText).substring(0, 200)}`);
          doc.fontSize(11).text(`Type: ${String(type).substring(0, 100)}`);
          doc.fontSize(11).text(`Severity: ${String(severity).substring(0, 100)}`);
          doc.fontSize(11).text(`Explanation: ${String(explanation).substring(0, 300)}`);
          doc.moveDown();
        });
      } else {
        doc.fontSize(12).text('No clauses available.');
      }
      doc.moveDown(1.5);

      // Recommendations
      doc.fontSize(18).text('Recommendations', { underline: true });
      doc.moveDown(0.5);
      const recommendations = analysis.recommendations || [
        'Review risky clauses carefully.',
        'Avoid policies with excessive tracking.',
        'Check third-party sharing permissions.',
        'Read auto-renewal conditions.',
        'Ensure GDPR/privacy compliance.',
      ];
      recommendations.forEach((r, i) => doc.fontSize(12).text(`${i + 1}. ${r}`));

      doc.moveDown(2);
      doc.fontSize(10).text('Generated by PolicyGuard AI', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = {
  generatePdfReport,
};
